/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InterrogationRouteImport } from './routes/interrogation'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerdictResultRouteImport } from './routes/verdict.$result'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const InterrogationRoute = InterrogationRouteImport.update({
  id: '/interrogation',
  path: '/interrogation',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerdictResultRoute = VerdictResultRouteImport.update({
  id: '/verdict/$result',
  path: '/verdict/$result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/interrogation': typeof InterrogationRoute
  '/api/chat': typeof ApiChatRoute
  '/api/download': typeof ApiDownloadRoute
  '/verdict/$result': typeof VerdictResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/interrogation': typeof InterrogationRoute
  '/api/chat': typeof ApiChatRoute
  '/api/download': typeof ApiDownloadRoute
  '/verdict/$result': typeof VerdictResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/interrogation': typeof InterrogationRoute
  '/api/chat': typeof ApiChatRoute
  '/api/download': typeof ApiDownloadRoute
  '/verdict/$result': typeof VerdictResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefing'
    | '/interrogation'
    | '/api/chat'
    | '/api/download'
    | '/verdict/$result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefing'
    | '/interrogation'
    | '/api/chat'
    | '/api/download'
    | '/verdict/$result'
  id:
    | '__root__'
    | '/'
    | '/briefing'
    | '/interrogation'
    | '/api/chat'
    | '/api/download'
    | '/verdict/$result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  InterrogationRoute: typeof InterrogationRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  VerdictResultRoute: typeof VerdictResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/interrogation': {
      id: '/interrogation'
      path: '/interrogation'
      fullPath: '/interrogation'
      preLoaderRoute: typeof InterrogationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verdict/$result': {
      id: '/verdict/$result'
      path: '/verdict/$result'
      fullPath: '/verdict/$result'
      preLoaderRoute: typeof VerdictResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  InterrogationRoute: InterrogationRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  VerdictResultRoute: VerdictResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
